name: Build and Push Docker Image
on:
  push:
    branches:
      - prod

concurrency:
  group: build-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mleng_sayhi

    steps:
      - name: Inject timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.TIMESTAMP }}
            ${{ env.IMAGE }}:latest
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
