name: Python Checks
on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pylint black mypy pytest || true

      - name: Run pylint (non-blocking)
        run: |
          export PYTHONPATH=.
          pylint app.py || true

      - name: Run pytest
        run: |
          export PYTHONPATH=.
          pytest -q
